server:
  port: 8090
# ?????
spring:
  datasource:
    username: root
    password: zhou
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/redis?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#redis ??
  redis:
    database: 0
    host: 192.168.1.107
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    timeout: 5000ms
# ??sql ??
  jpa:
    show-sql: true


