# application.yml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatisplus?serverTimezone=Asia/Shanghai
    username: root
    password: zhou

#\u5F00\u542FSQL\u8BED\u53E5\u6253\u5370
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

