server:
  port: 8090
#配置数据库连接
spring:
  datasource: #
    url: jdbc:mysql://localhost:3306/springbootMybatis?characterEncoding=UTF8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zhou

# mybatis xml文件配置
mybatis:
  type-aliases-package: com.yiwobao.springboot_03_thymeleaf.pojo #配置pojo别名  这样在mybatis xml中写全类名了
  mapper-locations: classpath:mapper/*Mapper.xml

#配置显示sql执行语句
logging:
  level:
      com:
        yiwobao:
          springboot_03_thymeleaf:
            dao: debug
